# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _broccoli_base
else:
    import _broccoli_base

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


EPI = _broccoli_base.EPI
MNI = _broccoli_base.MNI
MATLAB = _broccoli_base.MATLAB
PYTHON = _broccoli_base.PYTHON
BASH = _broccoli_base.BASH
CCA = _broccoli_base.CCA
GLM = _broccoli_base.GLM
SILENT = _broccoli_base.SILENT
VERBOSE = _broccoli_base.VERBOSE
NO = _broccoli_base.NO
YES = _broccoli_base.YES
RAW = _broccoli_base.RAW
NIFTI = _broccoli_base.NIFTI
DISCARD_DISPLACEMENT_FIELD = _broccoli_base.DISCARD_DISPLACEMENT_FIELD
KEEP_DISPLACEMENT_FIELD = _broccoli_base.KEEP_DISPLACEMENT_FIELD
FLOAT = _broccoli_base.FLOAT
INT32 = _broccoli_base.INT32
INT16 = _broccoli_base.INT16
UINT32 = _broccoli_base.UINT32
UINT16 = _broccoli_base.UINT16
DOUBLE = _broccoli_base.DOUBLE
UINT8 = _broccoli_base.UINT8
SLICE_TIMING_CORRECTION = _broccoli_base.SLICE_TIMING_CORRECTION
MOTION_CORRECTION = _broccoli_base.MOTION_CORRECTION
SMOOTHING = _broccoli_base.SMOOTHING
DETRENDING = _broccoli_base.DETRENDING
STATISTICAL_ANALYSIS = _broccoli_base.STATISTICAL_ANALYSIS
PERMUTATION_TEST = _broccoli_base.PERMUTATION_TEST
COPY = _broccoli_base.COPY
CONVOLVE = _broccoli_base.CONVOLVE
PHASEDC = _broccoli_base.PHASEDC
PHASEG = _broccoli_base.PHASEG
AH2D = _broccoli_base.AH2D
EQSYSTEM = _broccoli_base.EQSYSTEM
INTERPOLATION = _broccoli_base.INTERPOLATION
DONT_CALCULATE_VOXEL_LABELS = _broccoli_base.DONT_CALCULATE_VOXEL_LABELS
CALCULATE_VOXEL_LABELS = _broccoli_base.CALCULATE_VOXEL_LABELS
DONT_CALCULATE_CLUSTER_MASS = _broccoli_base.DONT_CALCULATE_CLUSTER_MASS
CALCULATE_CLUSTER_MASS = _broccoli_base.CALCULATE_CLUSTER_MASS
VOXEL = _broccoli_base.VOXEL
CLUSTER_EXTENT = _broccoli_base.CLUSTER_EXTENT
CLUSTER_MASS = _broccoli_base.CLUSTER_MASS
TFCE = _broccoli_base.TFCE
VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_ROWS = _broccoli_base.VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_ROWS
VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_ROWS = _broccoli_base.VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_ROWS
VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_ROWS = _broccoli_base.VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_ROWS
VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_COLUMNS = _broccoli_base.VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_COLUMNS
VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_COLUMNS = _broccoli_base.VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_COLUMNS
VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_COLUMNS = _broccoli_base.VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_COLUMNS
VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_RODS = _broccoli_base.VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_RODS
VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_RODS = _broccoli_base.VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_RODS
VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_RODS = _broccoli_base.VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_RODS
NOT_SKULL_STRIPPED = _broccoli_base.NOT_SKULL_STRIPPED
SKULL_STRIPPED = _broccoli_base.SKULL_STRIPPED
HALO = _broccoli_base.HALO
VALID_FILTER_RESPONSES_X_CONVOLUTION_2D_24KB = _broccoli_base.VALID_FILTER_RESPONSES_X_CONVOLUTION_2D_24KB
VALID_FILTER_RESPONSES_Y_CONVOLUTION_2D_24KB = _broccoli_base.VALID_FILTER_RESPONSES_Y_CONVOLUTION_2D_24KB
VALID_FILTER_RESPONSES_X_CONVOLUTION_2D_32KB = _broccoli_base.VALID_FILTER_RESPONSES_X_CONVOLUTION_2D_32KB
VALID_FILTER_RESPONSES_Y_CONVOLUTION_2D_32KB = _broccoli_base.VALID_FILTER_RESPONSES_Y_CONVOLUTION_2D_32KB
TTEST = _broccoli_base.TTEST
FTEST = _broccoli_base.FTEST
GROUP_MEAN = _broccoli_base.GROUP_MEAN
TWOSAMPLE = _broccoli_base.TWOSAMPLE
CORRELATION = _broccoli_base.CORRELATION
UP = _broccoli_base.UP
DOWN = _broccoli_base.DOWN
UP_INTERLEAVED = _broccoli_base.UP_INTERLEAVED
DOWN_INTERLEAVED = _broccoli_base.DOWN_INTERLEAVED
CUSTOM = _broccoli_base.CUSTOM
UNDEFINED = _broccoli_base.UNDEFINED
TRANSLATION = _broccoli_base.TRANSLATION
RIGID = _broccoli_base.RIGID
AFFINE = _broccoli_base.AFFINE
NEAREST = _broccoli_base.NEAREST
LINEAR = _broccoli_base.LINEAR
CUBIC = _broccoli_base.CUBIC
DO_OVERWRITE = _broccoli_base.DO_OVERWRITE
NO_OVERWRITE = _broccoli_base.NO_OVERWRITE
PI = _broccoli_base.PI
INITIAL_MM_T1_Z_CUT = _broccoli_base.INITIAL_MM_T1_Z_CUT
SUCCESS = _broccoli_base.SUCCESS
FAIL = _broccoli_base.FAIL
LOWPASS = _broccoli_base.LOWPASS
RANDOM = _broccoli_base.RANDOM
NVIDIA = _broccoli_base.NVIDIA
INTEL = _broccoli_base.INTEL
AMD = _broccoli_base.AMD
APPLE = _broccoli_base.APPLE
NUMBER_OF_FILTERS_FOR_NONLINEAR_REGISTRATION = _broccoli_base.NUMBER_OF_FILTERS_FOR_NONLINEAR_REGISTRATION
CL_SUCCESS = _broccoli_base.CL_SUCCESS
CL_DEVICE_NOT_FOUND = _broccoli_base.CL_DEVICE_NOT_FOUND
CL_DEVICE_NOT_AVAILABLE = _broccoli_base.CL_DEVICE_NOT_AVAILABLE
CL_COMPILER_NOT_AVAILABLE = _broccoli_base.CL_COMPILER_NOT_AVAILABLE
CL_MEM_OBJECT_ALLOCATION_FAILURE = _broccoli_base.CL_MEM_OBJECT_ALLOCATION_FAILURE
CL_OUT_OF_RESOURCES = _broccoli_base.CL_OUT_OF_RESOURCES
CL_OUT_OF_HOST_MEMORY = _broccoli_base.CL_OUT_OF_HOST_MEMORY
CL_PROFILING_INFO_NOT_AVAILABLE = _broccoli_base.CL_PROFILING_INFO_NOT_AVAILABLE
CL_MEM_COPY_OVERLAP = _broccoli_base.CL_MEM_COPY_OVERLAP
CL_IMAGE_FORMAT_MISMATCH = _broccoli_base.CL_IMAGE_FORMAT_MISMATCH
CL_IMAGE_FORMAT_NOT_SUPPORTED = _broccoli_base.CL_IMAGE_FORMAT_NOT_SUPPORTED
CL_BUILD_PROGRAM_FAILURE = _broccoli_base.CL_BUILD_PROGRAM_FAILURE
CL_MAP_FAILURE = _broccoli_base.CL_MAP_FAILURE
CL_INVALID_VALUE = _broccoli_base.CL_INVALID_VALUE
CL_INVALID_DEVICE_TYPE = _broccoli_base.CL_INVALID_DEVICE_TYPE
CL_INVALID_PLATFORM = _broccoli_base.CL_INVALID_PLATFORM
CL_INVALID_DEVICE = _broccoli_base.CL_INVALID_DEVICE
CL_INVALID_CONTEXT = _broccoli_base.CL_INVALID_CONTEXT
CL_INVALID_QUEUE_PROPERTIES = _broccoli_base.CL_INVALID_QUEUE_PROPERTIES
CL_INVALID_COMMAND_QUEUE = _broccoli_base.CL_INVALID_COMMAND_QUEUE
CL_INVALID_HOST_PTR = _broccoli_base.CL_INVALID_HOST_PTR
CL_INVALID_MEM_OBJECT = _broccoli_base.CL_INVALID_MEM_OBJECT
CL_INVALID_IMAGE_FORMAT_DESCRIPTOR = _broccoli_base.CL_INVALID_IMAGE_FORMAT_DESCRIPTOR
CL_INVALID_IMAGE_SIZE = _broccoli_base.CL_INVALID_IMAGE_SIZE
CL_INVALID_SAMPLER = _broccoli_base.CL_INVALID_SAMPLER
CL_INVALID_BINARY = _broccoli_base.CL_INVALID_BINARY
CL_INVALID_BUILD_OPTIONS = _broccoli_base.CL_INVALID_BUILD_OPTIONS
CL_INVALID_PROGRAM = _broccoli_base.CL_INVALID_PROGRAM
CL_INVALID_PROGRAM_EXECUTABLE = _broccoli_base.CL_INVALID_PROGRAM_EXECUTABLE
CL_INVALID_KERNEL_NAME = _broccoli_base.CL_INVALID_KERNEL_NAME
CL_INVALID_KERNEL_DEFINITION = _broccoli_base.CL_INVALID_KERNEL_DEFINITION
CL_INVALID_KERNEL = _broccoli_base.CL_INVALID_KERNEL
CL_INVALID_ARG_INDEX = _broccoli_base.CL_INVALID_ARG_INDEX
CL_INVALID_ARG_VALUE = _broccoli_base.CL_INVALID_ARG_VALUE
CL_INVALID_ARG_SIZE = _broccoli_base.CL_INVALID_ARG_SIZE
CL_INVALID_KERNEL_ARGS = _broccoli_base.CL_INVALID_KERNEL_ARGS
CL_INVALID_WORK_DIMENSION = _broccoli_base.CL_INVALID_WORK_DIMENSION
CL_INVALID_WORK_GROUP_SIZE = _broccoli_base.CL_INVALID_WORK_GROUP_SIZE
CL_INVALID_WORK_ITEM_SIZE = _broccoli_base.CL_INVALID_WORK_ITEM_SIZE
CL_INVALID_GLOBAL_OFFSET = _broccoli_base.CL_INVALID_GLOBAL_OFFSET
CL_INVALID_EVENT_WAIT_LIST = _broccoli_base.CL_INVALID_EVENT_WAIT_LIST
CL_INVALID_EVENT = _broccoli_base.CL_INVALID_EVENT
CL_INVALID_OPERATION = _broccoli_base.CL_INVALID_OPERATION
CL_INVALID_GL_OBJECT = _broccoli_base.CL_INVALID_GL_OBJECT
CL_INVALID_BUFFER_SIZE = _broccoli_base.CL_INVALID_BUFFER_SIZE
CL_INVALID_MIP_LEVEL = _broccoli_base.CL_INVALID_MIP_LEVEL
CL_INVALID_GLOBAL_WORK_SIZE = _broccoli_base.CL_INVALID_GLOBAL_WORK_SIZE
class float2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_broccoli_base.float2_x_get, _broccoli_base.float2_x_set)
    y = property(_broccoli_base.float2_y_get, _broccoli_base.float2_y_set)

    def __init__(self):
        _broccoli_base.float2_swiginit(self, _broccoli_base.new_float2())
    __swig_destroy__ = _broccoli_base.delete_float2

# Register float2 in _broccoli_base:
_broccoli_base.float2_swigregister(float2)
X = _broccoli_base.X
Y = _broccoli_base.Y
Z = _broccoli_base.Z
class Coords3D(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        _broccoli_base.Coords3D_swiginit(self, _broccoli_base.new_Coords3D(*args))

    def __getitem__(self, i):
        return _broccoli_base.Coords3D___getitem__(self, i)

    def __setitem__(self, i, v):
        return _broccoli_base.Coords3D___setitem__(self, i, v)

    def __repr__(self):
        return _broccoli_base.Coords3D___repr__(self)
    __swig_destroy__ = _broccoli_base.delete_Coords3D

# Register Coords3D in _broccoli_base:
_broccoli_base.Coords3D_swigregister(Coords3D)
class BROCCOLI_LIB(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _broccoli_base.BROCCOLI_LIB_swiginit(self, _broccoli_base.new_BROCCOLI_LIB(*args))
    __swig_destroy__ = _broccoli_base.delete_BROCCOLI_LIB

    def SetDebug(self, debug):
        return _broccoli_base.BROCCOLI_LIB_SetDebug(self, debug)

    def SetPrint(self, _print):
        return _broccoli_base.BROCCOLI_LIB_SetPrint(self, _print)

    def SetVerbose(self, verbos):
        return _broccoli_base.BROCCOLI_LIB_SetVerbose(self, verbos)

    def SetWrapper(self, wrapper):
        return _broccoli_base.BROCCOLI_LIB_SetWrapper(self, wrapper)

    def SetAllocatedHostMemory(self, allocated):
        return _broccoli_base.BROCCOLI_LIB_SetAllocatedHostMemory(self, allocated)

    def SetMask(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetMask(self, input)

    def SetEPIMask(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetEPIMask(self, input)

    def SetSmoothedEPIMask(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetSmoothedEPIMask(self, input)

    def SetAutoMask(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetAutoMask(self, arg2)

    def SetTemporalDerivatives(self, TD):
        return _broccoli_base.BROCCOLI_LIB_SetTemporalDerivatives(self, TD)

    def SetBayesian(self, B):
        return _broccoli_base.BROCCOLI_LIB_SetBayesian(self, B)

    def SetRegressOnly(self, R):
        return _broccoli_base.BROCCOLI_LIB_SetRegressOnly(self, R)

    def SetPreprocessingOnly(self, B):
        return _broccoli_base.BROCCOLI_LIB_SetPreprocessingOnly(self, B)

    def SetBetasOnly(self, B):
        return _broccoli_base.BROCCOLI_LIB_SetBetasOnly(self, B)

    def SetContrastsOnly(self, C):
        return _broccoli_base.BROCCOLI_LIB_SetContrastsOnly(self, C)

    def SetBetasAndContrastsOnly(self, BC):
        return _broccoli_base.BROCCOLI_LIB_SetBetasAndContrastsOnly(self, BC)

    def SetRegressMotion(self, R):
        return _broccoli_base.BROCCOLI_LIB_SetRegressMotion(self, R)

    def SetRegressGlobalMean(self, R):
        return _broccoli_base.BROCCOLI_LIB_SetRegressGlobalMean(self, R)

    def SetRegressConfounds(self, R):
        return _broccoli_base.BROCCOLI_LIB_SetRegressConfounds(self, R)

    def SetPermuteFirstLevel(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetPermuteFirstLevel(self, arg2)

    def SetConfoundRegressors(self, X_GLM):
        return _broccoli_base.BROCCOLI_LIB_SetConfoundRegressors(self, X_GLM)

    def SetNumberOfGLMRegressors(self, NR):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfGLMRegressors(self, NR)

    def SetNumberOfDetrendingRegressors(self, NR):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfDetrendingRegressors(self, NR)

    def SetNumberOfConfoundRegressors(self, NR):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfConfoundRegressors(self, NR)

    def SetNumberOfContrasts(self, NC):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfContrasts(self, NC)

    def SetDesignMatrix(self, X_GLM, xtxxt_GLM):
        return _broccoli_base.BROCCOLI_LIB_SetDesignMatrix(self, X_GLM, xtxxt_GLM)

    def SetCorrectClasses(self, C, D):
        return _broccoli_base.BROCCOLI_LIB_SetCorrectClasses(self, C, D)

    def SetContrasts(self, contrasts):
        return _broccoli_base.BROCCOLI_LIB_SetContrasts(self, contrasts)

    def SetGLMScalars(self, ctxtxc):
        return _broccoli_base.BROCCOLI_LIB_SetGLMScalars(self, ctxtxc)

    def SetNumberOfPermutations(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfPermutations(self, arg2)

    def SetNumberOfGroupPermutations(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfGroupPermutations(self, arg2)

    def SetNumberOfMCMCIterations(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfMCMCIterations(self, arg2)

    def SetBetaSpace(self, space):
        return _broccoli_base.BROCCOLI_LIB_SetBetaSpace(self, space)

    def SetStatisticalTest(self, test):
        return _broccoli_base.BROCCOLI_LIB_SetStatisticalTest(self, test)

    def SetGroupDesigns(self, designs):
        return _broccoli_base.BROCCOLI_LIB_SetGroupDesigns(self, designs)

    def SetInferenceMode(self, mode):
        return _broccoli_base.BROCCOLI_LIB_SetInferenceMode(self, mode)

    def SetClusterDefiningThreshold(self, threshold):
        return _broccoli_base.BROCCOLI_LIB_SetClusterDefiningThreshold(self, threshold)

    def SetPermutationMatrix(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetPermutationMatrix(self, arg2)

    def SetPermutationMatrices(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetPermutationMatrices(self, arg2)

    def SetSignMatrix(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSignMatrix(self, arg2)

    def SetPermutationFileUsage(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetPermutationFileUsage(self, arg2)

    def SetDoAllPermutations(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetDoAllPermutations(self, arg2)

    def SetRawRegressors(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetRawRegressors(self, arg2)

    def SetRawDesignMatrix(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetRawDesignMatrix(self, arg2)

    def SetCustomReferenceSlice(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetCustomReferenceSlice(self, arg2)

    def SetNumberOfICAComponents(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfICAComponents(self, arg2)

    def SetVarianceToSaveBeforeICA(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetVarianceToSaveBeforeICA(self, arg2)

    def SetZScore(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetZScore(self, arg2)

    def SetSmoothingFilters(self, smoothing_filter_x, smoothing_filter_y, smoothing_filter_z):
        return _broccoli_base.BROCCOLI_LIB_SetSmoothingFilters(self, smoothing_filter_x, smoothing_filter_y, smoothing_filter_z)

    def SetSmoothingType(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSmoothingType(self, arg2)

    def SetEPISmoothingAmount(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetEPISmoothingAmount(self, arg2)

    def SetARSmoothingAmount(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetARSmoothingAmount(self, arg2)

    def SetApplySmoothing(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetApplySmoothing(self, arg2)

    def SetPrecenterRegistration(self, center):
        return _broccoli_base.BROCCOLI_LIB_SetPrecenterRegistration(self, center)

    def SetImageRegistrationFilterSize(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetImageRegistrationFilterSize(self, N)

    def SetLinearImageRegistrationFilters(self, qf1r, qf1i, qf2r, qf2i, qf3r, qf3i):
        return _broccoli_base.BROCCOLI_LIB_SetLinearImageRegistrationFilters(self, qf1r, qf1i, qf2r, qf2i, qf3r, qf3i)

    def SetNonLinearImageRegistrationFilters(self, qf1r, qf1i, qf2r, qf2i, q3r, q3i, qf4r, qf4i, qf5r, qf5i, q6r, q6i):
        return _broccoli_base.BROCCOLI_LIB_SetNonLinearImageRegistrationFilters(self, qf1r, qf1i, qf2r, qf2i, q3r, q3i, qf4r, qf4i, qf5r, qf5i, q6r, q6i)

    def SetProjectionTensorMatrixFirstFilter(self, m11, m12, m13, m22, m23, m33):
        return _broccoli_base.BROCCOLI_LIB_SetProjectionTensorMatrixFirstFilter(self, m11, m12, m13, m22, m23, m33)

    def SetProjectionTensorMatrixSecondFilter(self, m11, m12, m13, m22, m23, m33):
        return _broccoli_base.BROCCOLI_LIB_SetProjectionTensorMatrixSecondFilter(self, m11, m12, m13, m22, m23, m33)

    def SetProjectionTensorMatrixThirdFilter(self, m11, m12, m13, m22, m23, m33):
        return _broccoli_base.BROCCOLI_LIB_SetProjectionTensorMatrixThirdFilter(self, m11, m12, m13, m22, m23, m33)

    def SetProjectionTensorMatrixFourthFilter(self, m11, m12, m13, m22, m23, m33):
        return _broccoli_base.BROCCOLI_LIB_SetProjectionTensorMatrixFourthFilter(self, m11, m12, m13, m22, m23, m33)

    def SetProjectionTensorMatrixFifthFilter(self, m11, m12, m13, m22, m23, m33):
        return _broccoli_base.BROCCOLI_LIB_SetProjectionTensorMatrixFifthFilter(self, m11, m12, m13, m22, m23, m33)

    def SetProjectionTensorMatrixSixthFilter(self, m11, m12, m13, m22, m23, m33):
        return _broccoli_base.BROCCOLI_LIB_SetProjectionTensorMatrixSixthFilter(self, m11, m12, m13, m22, m23, m33)

    def SetFilterDirections(self, x, y, z):
        return _broccoli_base.BROCCOLI_LIB_SetFilterDirections(self, x, y, z)

    def SetNumberOfIterationsForLinearImageRegistration(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfIterationsForLinearImageRegistration(self, N)

    def SetNumberOfIterationsForNonLinearImageRegistration(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfIterationsForNonLinearImageRegistration(self, N)

    def SetNumberOfIterationsForMotionCorrection(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfIterationsForMotionCorrection(self, N)

    def SetChangeMotionCorrectionReferenceVolume(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetChangeMotionCorrectionReferenceVolume(self, arg2)

    def SetMotionCorrectionReferenceVolume(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetMotionCorrectionReferenceVolume(self, arg2)

    def SetApplyMotionCorrection(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetApplyMotionCorrection(self, arg2)

    def SetCoarsestScaleT1MNI(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetCoarsestScaleT1MNI(self, N)

    def SetCoarsestScaleEPIT1(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetCoarsestScaleEPIT1(self, N)

    def SetMMT1ZCUT(self, mm):
        return _broccoli_base.BROCCOLI_LIB_SetMMT1ZCUT(self, mm)

    def SetMMEPIZCUT(self, mm):
        return _broccoli_base.BROCCOLI_LIB_SetMMEPIZCUT(self, mm)

    def SetInterpolationMode(self, mode):
        return _broccoli_base.BROCCOLI_LIB_SetInterpolationMode(self, mode)

    def SetTsigma(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetTsigma(self, arg2)

    def SetEsigma(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetEsigma(self, arg2)

    def SetDsigma(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetDsigma(self, arg2)

    def SetDoSkullstrip(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetDoSkullstrip(self, arg2)

    def SetDoSkullstripOriginal(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetDoSkullstripOriginal(self, arg2)

    def SetCustomSliceTimes(self, times):
        return _broccoli_base.BROCCOLI_LIB_SetCustomSliceTimes(self, times)

    def SetApplySliceTimingCorrection(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetApplySliceTimingCorrection(self, arg2)

    def SetEPIVoxelSizeX(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetEPIVoxelSizeX(self, value)

    def SetEPIVoxelSizeY(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetEPIVoxelSizeY(self, value)

    def SetEPIVoxelSizeZ(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetEPIVoxelSizeZ(self, value)

    def SetEPITR(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetEPITR(self, value)

    def SetEPISliceOrder(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetEPISliceOrder(self, value)

    def SetEPIWidth(self, w):
        return _broccoli_base.BROCCOLI_LIB_SetEPIWidth(self, w)

    def SetEPIHeight(self, h):
        return _broccoli_base.BROCCOLI_LIB_SetEPIHeight(self, h)

    def SetEPIDepth(self, d):
        return _broccoli_base.BROCCOLI_LIB_SetEPIDepth(self, d)

    def SetEPITimepoints(self, t):
        return _broccoli_base.BROCCOLI_LIB_SetEPITimepoints(self, t)

    def SetEPITimepointsPerRun(self, t):
        return _broccoli_base.BROCCOLI_LIB_SetEPITimepointsPerRun(self, t)

    def SetNumberOfRuns(self, r):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfRuns(self, r)

    def SetT1VoxelSizeX(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetT1VoxelSizeX(self, value)

    def SetT1VoxelSizeY(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetT1VoxelSizeY(self, value)

    def SetT1VoxelSizeZ(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetT1VoxelSizeZ(self, value)

    def SetT1Width(self, w):
        return _broccoli_base.BROCCOLI_LIB_SetT1Width(self, w)

    def SetT1Height(self, h):
        return _broccoli_base.BROCCOLI_LIB_SetT1Height(self, h)

    def SetT1Depth(self, d):
        return _broccoli_base.BROCCOLI_LIB_SetT1Depth(self, d)

    def SetT1Timepoints(self, t):
        return _broccoli_base.BROCCOLI_LIB_SetT1Timepoints(self, t)

    def SetMNIVoxelSizeX(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetMNIVoxelSizeX(self, value)

    def SetMNIVoxelSizeY(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetMNIVoxelSizeY(self, value)

    def SetMNIVoxelSizeZ(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetMNIVoxelSizeZ(self, value)

    def SetMNIWidth(self, w):
        return _broccoli_base.BROCCOLI_LIB_SetMNIWidth(self, w)

    def SetMNIHeight(self, h):
        return _broccoli_base.BROCCOLI_LIB_SetMNIHeight(self, h)

    def SetMNIDepth(self, d):
        return _broccoli_base.BROCCOLI_LIB_SetMNIDepth(self, d)

    def SetInputfMRIVolumes(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputfMRIVolumes(self, input)

    def SetInputCertainty(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputCertainty(self, input)

    def SetInputEPIVolume(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputEPIVolume(self, input)

    def SetInputT1Volume(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputT1Volume(self, input)

    def SetInputMNIVolume(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputMNIVolume(self, input)

    def SetInputMNIBrainVolume(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputMNIBrainVolume(self, input)

    def SetInputMNIBrainMask(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputMNIBrainMask(self, input)

    def SetInputFirstLevelResults(self, input):
        return _broccoli_base.BROCCOLI_LIB_SetInputFirstLevelResults(self, input)

    def SetNumberOfSubjects(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfSubjects(self, N)

    def SetNumberOfSubjectsGroup1(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfSubjectsGroup1(self, N)

    def SetNumberOfSubjectsGroup2(self, N):
        return _broccoli_base.BROCCOLI_LIB_SetNumberOfSubjectsGroup2(self, N)

    def SetOutputBetaVolumesEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputBetaVolumesEPI(self, output)

    def SetOutputBetaVolumesT1(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputBetaVolumesT1(self, output)

    def SetOutputBetaVolumesMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputBetaVolumesMNI(self, output)

    def SetOutputBetaVolumesNoWhiteningEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputBetaVolumesNoWhiteningEPI(self, output)

    def SetOutputBetaVolumesNoWhiteningT1(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputBetaVolumesNoWhiteningT1(self, output)

    def SetOutputBetaVolumesNoWhiteningMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputBetaVolumesNoWhiteningMNI(self, output)

    def SetOutputContrastVolumesEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputContrastVolumesEPI(self, output)

    def SetOutputContrastVolumesT1(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputContrastVolumesT1(self, output)

    def SetOutputContrastVolumesMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputContrastVolumesMNI(self, output)

    def SetOutputContrastVolumesNoWhiteningEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputContrastVolumesNoWhiteningEPI(self, output)

    def SetOutputContrastVolumesNoWhiteningT1(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputContrastVolumesNoWhiteningT1(self, output)

    def SetOutputContrastVolumesNoWhiteningMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputContrastVolumesNoWhiteningMNI(self, output)

    def SetOutputStatisticalMapsEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputStatisticalMapsEPI(self, output)

    def SetOutputStatisticalMapsT1(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputStatisticalMapsT1(self, output)

    def SetOutputStatisticalMapsMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputStatisticalMapsMNI(self, output)

    def SetOutputStatisticalMapsNoWhiteningEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputStatisticalMapsNoWhiteningEPI(self, output)

    def SetOutputStatisticalMapsNoWhiteningT1(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputStatisticalMapsNoWhiteningT1(self, output)

    def SetOutputStatisticalMapsNoWhiteningMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputStatisticalMapsNoWhiteningMNI(self, output)

    def SetOutputResidualsEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputResidualsEPI(self, output)

    def SetOutputResidualsMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputResidualsMNI(self, output)

    def SetOutputfMRIVolumesMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputfMRIVolumesMNI(self, output)

    def SetOutputResidualVariances(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputResidualVariances(self, output)

    def SetOutputPValuesEPI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPValuesEPI(self, output)

    def SetOutputPValuesT1(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPValuesT1(self, output)

    def SetOutputPValuesMNI(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPValuesMNI(self, output)

    def SetOutputEPIMask(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputEPIMask(self, arg2)

    def SetOutputMNIMask(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputMNIMask(self, arg2)

    def SetOutputClusterIndices(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputClusterIndices(self, arg2)

    def SetOutputLargestCluster(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputLargestCluster(self, arg2)

    def SetOutputDesignMatrix(self, X_GLM, xtxxt_GLM):
        return _broccoli_base.BROCCOLI_LIB_SetOutputDesignMatrix(self, X_GLM, xtxxt_GLM)

    def SetOutputWhitenedModels(self, whitened_models):
        return _broccoli_base.BROCCOLI_LIB_SetOutputWhitenedModels(self, whitened_models)

    def SetOutputMotionParameters(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputMotionParameters(self, output)

    def SetOutputT1MNIRegistrationParameters(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputT1MNIRegistrationParameters(self, output)

    def SetOutputEPIT1RegistrationParameters(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputEPIT1RegistrationParameters(self, output)

    def SetOutputEPIMNIRegistrationParameters(self, output):
        return _broccoli_base.BROCCOLI_LIB_SetOutputEPIMNIRegistrationParameters(self, output)

    def SetOutputQuadratureFilterResponses(self, *args):
        return _broccoli_base.BROCCOLI_LIB_SetOutputQuadratureFilterResponses(self, *args)

    def SetOutputTensorComponents(self, arg2, arg3, arg4, arg5, arg6, arg7):
        return _broccoli_base.BROCCOLI_LIB_SetOutputTensorComponents(self, arg2, arg3, arg4, arg5, arg6, arg7)

    def SetOutputDisplacementField(self, arg2, arg3, arg4):
        return _broccoli_base.BROCCOLI_LIB_SetOutputDisplacementField(self, arg2, arg3, arg4)

    def SetOutputPhaseDifferences(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPhaseDifferences(self, arg2)

    def SetOutputPhaseCertainties(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPhaseCertainties(self, arg2)

    def SetOutputPhaseGradients(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPhaseGradients(self, arg2)

    def SetOutputAlignedT1VolumeLinear(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAlignedT1VolumeLinear(self, arg2)

    def SetOutputAlignedT1VolumeNonLinear(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAlignedT1VolumeNonLinear(self, arg2)

    def SetOutputAlignedEPIVolumeT1(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAlignedEPIVolumeT1(self, arg2)

    def SetOutputAlignedEPIVolumeMNI(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAlignedEPIVolumeMNI(self, arg2)

    def SetOutputAlignedEPIVolumeMNILinear(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAlignedEPIVolumeMNILinear(self, arg2)

    def SetOutputAlignedEPIVolumeMNINonlinear(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAlignedEPIVolumeMNINonlinear(self, arg2)

    def SetOutputSkullstrippedT1Volume(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputSkullstrippedT1Volume(self, arg2)

    def SetOutputInterpolatedT1Volume(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputInterpolatedT1Volume(self, arg2)

    def SetOutputInterpolatedEPIVolume(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputInterpolatedEPIVolume(self, arg2)

    def SetOutputDownsampledVolume(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputDownsampledVolume(self, arg2)

    def SetOutputMotionCorrectedfMRIVolumes(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputMotionCorrectedfMRIVolumes(self, arg2)

    def SetOutputSliceTimingCorrectedfMRIVolumes(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputSliceTimingCorrectedfMRIVolumes(self, arg2)

    def SetOutputSmoothedfMRIVolumes(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputSmoothedfMRIVolumes(self, arg2)

    def SetOutputDetrendedfMRIVolumes(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputDetrendedfMRIVolumes(self, arg2)

    def SetOutputWhitenedfMRIVolumes(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputWhitenedfMRIVolumes(self, arg2)

    def SetOutputPermutedfMRIVolumes(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPermutedfMRIVolumes(self, arg2)

    def SetOutputPermutedFirstLevelResults(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPermutedFirstLevelResults(self, arg2)

    def SetOutputAREstimatesEPI(self, arg2, arg3, arg4, arg5):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAREstimatesEPI(self, arg2, arg3, arg4, arg5)

    def SetOutputAREstimatesT1(self, arg2, arg3, arg4, arg5):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAREstimatesT1(self, arg2, arg3, arg4, arg5)

    def SetOutputAREstimatesMNI(self, arg2, arg3, arg4, arg5):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAREstimatesMNI(self, arg2, arg3, arg4, arg5)

    def SetOutputSliceSums(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputSliceSums(self, arg2)

    def SetOutputTopSlice(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputTopSlice(self, arg2)

    def SetOutputPermutationDistribution(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPermutationDistribution(self, arg2)

    def SetOutputPermutationDistributions(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputPermutationDistributions(self, arg2)

    def SetOutputAMatrix(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputAMatrix(self, arg2)

    def SetOutputHVector(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetOutputHVector(self, arg2)

    def SetSignificanceLevel(self, value):
        return _broccoli_base.BROCCOLI_LIB_SetSignificanceLevel(self, value)

    def SetSaveDisplacementField(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveDisplacementField(self, arg2)

    def SetSaveInterpolatedT1(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveInterpolatedT1(self, arg2)

    def SetSaveAlignedT1MNILinear(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveAlignedT1MNILinear(self, arg2)

    def SetSaveAlignedT1MNINonLinear(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveAlignedT1MNINonLinear(self, arg2)

    def SetSaveAlignedEPIT1(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveAlignedEPIT1(self, arg2)

    def SetSaveAlignedEPIMNI(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveAlignedEPIMNI(self, arg2)

    def SetSaveEPIMask(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveEPIMask(self, arg2)

    def SetSaveMNIMask(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveMNIMask(self, arg2)

    def SetSaveSliceTimingCorrected(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveSliceTimingCorrected(self, arg2)

    def SetSaveMotionCorrected(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveMotionCorrected(self, arg2)

    def SetSaveSmoothed(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveSmoothed(self, arg2)

    def SetSaveActivityEPI(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveActivityEPI(self, arg2)

    def SetSaveActivityT1(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveActivityT1(self, arg2)

    def SetSaveDesignMatrix(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveDesignMatrix(self, arg2)

    def SetSaveAREstimatesEPI(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveAREstimatesEPI(self, arg2)

    def SetSaveAREstimatesT1(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveAREstimatesT1(self, arg2)

    def SetSaveAREstimatesMNI(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveAREstimatesMNI(self, arg2)

    def SetSaveUnwhitenedResults(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveUnwhitenedResults(self, arg2)

    def SetSaveResidualsEPI(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveResidualsEPI(self, arg2)

    def SetSaveResidualsMNI(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveResidualsMNI(self, arg2)

    def SetSaveResidualVariances(self, arg2):
        return _broccoli_base.BROCCOLI_LIB_SetSaveResidualVariances(self, arg2)

    def GetOpenCLInitiated(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLInitiated(self)

    def GetNumberOfOpenCLKernels(self):
        return _broccoli_base.BROCCOLI_LIB_GetNumberOfOpenCLKernels(self)

    def GetEPIVoxelSizeX(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPIVoxelSizeX(self)

    def GetEPIVoxelSizeY(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPIVoxelSizeY(self)

    def GetEPIVoxelSizeZ(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPIVoxelSizeZ(self)

    def GetEPITR(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPITR(self)

    def GetEPIWidth(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPIWidth(self)

    def GetEPIHeight(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPIHeight(self)

    def GetEPIDepth(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPIDepth(self)

    def GetEPITimepoints(self):
        return _broccoli_base.BROCCOLI_LIB_GetEPITimepoints(self)

    def GetT1Width(self):
        return _broccoli_base.BROCCOLI_LIB_GetT1Width(self)

    def GetT1Height(self):
        return _broccoli_base.BROCCOLI_LIB_GetT1Height(self)

    def GetT1Depth(self):
        return _broccoli_base.BROCCOLI_LIB_GetT1Depth(self)

    def GetSignificanceThreshold(self):
        return _broccoli_base.BROCCOLI_LIB_GetSignificanceThreshold(self)

    def GetNumberOfSignificantlyActiveVoxels(self):
        return _broccoli_base.BROCCOLI_LIB_GetNumberOfSignificantlyActiveVoxels(self)

    def GetNumberOfSignificantlyActiveClusters(self):
        return _broccoli_base.BROCCOLI_LIB_GetNumberOfSignificantlyActiveClusters(self)

    def GetNumberOfICAComponents(self):
        return _broccoli_base.BROCCOLI_LIB_GetNumberOfICAComponents(self)

    def GetKernelFileNames(self):
        return _broccoli_base.BROCCOLI_LIB_GetKernelFileNames(self)

    def GetNumberOfKernelFiles(self):
        return _broccoli_base.BROCCOLI_LIB_GetNumberOfKernelFiles(self)

    def GetOpenCLDeviceInfoChar(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLDeviceInfoChar(self)

    def GetOpenCLErrorMessage(self, error):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLErrorMessage(self, error)

    def GetOpenCLKernelName(self, kernel):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLKernelName(self, kernel)

    def GetOpenCLPlatformName(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLPlatformName(self)

    def GetOpenCLDeviceName(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLDeviceName(self)

    def GetOpenCLDeviceInfoString(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLDeviceInfoString(self)

    def GetOpenCLBuildInfo(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLBuildInfo(self)

    def GetOpenCLCreateKernelErrors(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLCreateKernelErrors(self)

    def GetOpenCLCreateBufferErrors(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLCreateBufferErrors(self)

    def GetOpenCLRunKernelErrors(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLRunKernelErrors(self)

    def GetOpenCLPlatformIDsError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLPlatformIDsError(self)

    def GetOpenCLDeviceIDsError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLDeviceIDsError(self)

    def GetOpenCLCreateContextError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLCreateContextError(self)

    def GetOpenCLContextInfoError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLContextInfoError(self)

    def GetOpenCLCreateCommandQueueError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLCreateCommandQueueError(self)

    def GetOpenCLCreateProgramError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLCreateProgramError(self)

    def GetOpenCLBuildProgramError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLBuildProgramError(self)

    def GetOpenCLProgramBuildInfoError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLProgramBuildInfoError(self)

    def GetOpenCLInitializationError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLInitializationError(self)

    def GetOpenCLError(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLError(self)

    def GetProgramBinarySize(self):
        return _broccoli_base.BROCCOLI_LIB_GetProgramBinarySize(self)

    def GetWrittenElements(self):
        return _broccoli_base.BROCCOLI_LIB_GetWrittenElements(self)

    def GetProcessingTimeSliceTimingCorrection(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeSliceTimingCorrection(self)

    def GetProcessingTimeMotionCorrection(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeMotionCorrection(self)

    def GetProcessingTimeSmoothing(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeSmoothing(self)

    def GetProcessingTimeDetrending(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeDetrending(self)

    def GetProcessingTimeStatisticalAnalysis(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeStatisticalAnalysis(self)

    def GetProcessingTimePermutationTest(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimePermutationTest(self)

    def GetProcessingTimeCopy(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeCopy(self)

    def GetProcessingTimeConvolution(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeConvolution(self)

    def GetProcessingTimePhaseDifferences(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimePhaseDifferences(self)

    def GetProcessingTimePhaseGradients(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimePhaseGradients(self)

    def GetProcessingTimeAH(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeAH(self)

    def GetProcessingTimeEquationSystem(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeEquationSystem(self)

    def GetProcessingTimeInterpolation(self):
        return _broccoli_base.BROCCOLI_LIB_GetProcessingTimeInterpolation(self)

    def PerformRegistrationTwoVolumesWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformRegistrationTwoVolumesWrapper(self)

    def TransformVolumesNonLinearWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_TransformVolumesNonLinearWrapper(self)

    def TransformVolumesLinearWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_TransformVolumesLinearWrapper(self)

    def CenterVolumesWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_CenterVolumesWrapper(self)

    def PerformSliceTimingCorrectionWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformSliceTimingCorrectionWrapper(self)

    def PerformMotionCorrectionWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformMotionCorrectionWrapper(self)

    def PerformSmoothingWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformSmoothingWrapper(self)

    def PerformSmoothingNormalizedWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformSmoothingNormalizedWrapper(self)

    def PerformSmoothingNormalizedHostWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformSmoothingNormalizedHostWrapper(self)

    def PerformGLMTTestFirstLevelWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMTTestFirstLevelWrapper(self)

    def PerformGLMFTestFirstLevelWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMFTestFirstLevelWrapper(self)

    def PerformGLMTTestSecondLevelWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMTTestSecondLevelWrapper(self)

    def PerformGLMFTestSecondLevelWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMFTestSecondLevelWrapper(self)

    def PerformGLMTTestFirstLevelPermutationWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMTTestFirstLevelPermutationWrapper(self)

    def PerformGLMFTestFirstLevelPermutationWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMFTestFirstLevelPermutationWrapper(self)

    def PerformSearchlightWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformSearchlightWrapper(self)

    def PerformMeanSecondLevelPermutationWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformMeanSecondLevelPermutationWrapper(self)

    def PerformGLMTTestSecondLevelPermutationWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMTTestSecondLevelPermutationWrapper(self)

    def PerformGLMFTestSecondLevelPermutationWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformGLMFTestSecondLevelPermutationWrapper(self)

    def PerformBayesianFirstLevelWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformBayesianFirstLevelWrapper(self)

    def PerformFirstLevelAnalysisWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformFirstLevelAnalysisWrapper(self)

    def PerformSecondLevelAnalysisWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformSecondLevelAnalysisWrapper(self)

    def PerformICAWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformICAWrapper(self)

    def PerformICADoubleWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformICADoubleWrapper(self)

    def PerformICACPUWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformICACPUWrapper(self)

    def PerformICADoubleCPUWrapper(self):
        return _broccoli_base.BROCCOLI_LIB_PerformICADoubleCPUWrapper(self)

    def GetOpenCLInfo(self):
        return _broccoli_base.BROCCOLI_LIB_GetOpenCLInfo(self)

    def GetBandwidth(self):
        return _broccoli_base.BROCCOLI_LIB_GetBandwidth(self)

    def OpenCLInitiate(self, OPENCL_PLATFORM, OPENCL_DEVICE):
        return _broccoli_base.BROCCOLI_LIB_OpenCLInitiate(self, OPENCL_PLATFORM, OPENCL_DEVICE)

# Register BROCCOLI_LIB in _broccoli_base:
_broccoli_base.BROCCOLI_LIB_swigregister(BROCCOLI_LIB)

